spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/producto/**
          filters:
            - StripPrefix= 2

        - id: cliente-service
          uri: cliente-service
          predicates:
            - Path=/api/cliente/**
          filters:
            - StripPrefix=2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT:9090}